[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:ekspedisi-quran-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /Users/agus/Herd/ekspedisi-quran/artisan queue:work database --sleep=3 --tries=3 --max-time=3600 --timeout=120
autostart=true
autorestart=true
user=agus
numprocs=2
redirect_stderr=true
stdout_logfile=/Users/agus/Herd/ekspedisi-quran/storage/logs/queue-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

[program:ekspedisi-quran-scheduler]
process_name=%(program_name)s
command=php /Users/agus/Herd/ekspedisi-quran/artisan schedule:work
autostart=true
autorestart=true
user=agus
numprocs=1
redirect_stderr=true
stdout_logfile=/Users/agus/Herd/ekspedisi-quran/storage/logs/scheduler.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5