[program:ekspedisi-queue-high]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/ekspedisi-quran/artisan queue:work redis-high --queue=high --sleep=3 --tries=3 --max-time=3600 --timeout=600 --memory=512
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/ekspedisi-queue-high.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=5
stopwaitsecs=3600