[program:ekspedisi-queue-certificates]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/ekspedisi-quran/artisan queue:work redis-certificates --queue=certificates --sleep=3 --tries=2 --max-time=7200 --timeout=3600 --memory=1024
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=3
redirect_stderr=true
stdout_logfile=/var/log/ekspedisi-queue-certificates.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=5
stopwaitsecs=7200