[program:ekspedisi-queue-low]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/ekspedisi-quran/artisan queue:work redis-low --queue=low --sleep=5 --tries=2 --max-time=7200 --timeout=1800 --memory=256
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/ekspedisi-queue-low.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=5
stopwaitsecs=7200