export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  DASHBOARD_ANALYTICS: 'dashboard.analytics',

  USERS_CREATE: 'users.create',
  USERS_READ: 'users.read',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  USERS_TOGGLE: 'users.toggle',

  ROLES_CREATE: 'roles.create',
  ROLES_READ: 'roles.read',
  ROLES_UPDATE: 'roles.update',
  ROLES_DELETE: 'roles.delete',

  PERMISSIONS_CREATE: 'permissions.create',
  PERMISSIONS_READ: 'permissions.read',
  PERMISSIONS_UPDATE: 'permissions.update',
  PERMISSIONS_DELETE: 'permissions.delete',

  DONATUR_CREATE: 'donatur.create',
  DONATUR_READ: 'donatur.read',
  DONATUR_UPDATE: 'donatur.update',
  DONATUR_DELETE: 'donatur.delete',
  DONATUR_IMPORT: 'donatur.import',
  DONATUR_EXPORT: 'donatur.export',

  SHIPMENTS_CREATE: 'shipments.create',
  SHIPMENTS_READ: 'shipments.read',
  SHIPMENTS_UPDATE: 'shipments.update',
  SHIPMENTS_DELETE: 'shipments.delete',
  SHIPMENTS_EXPORT: 'shipments.export',
  SHIPMENTS_TRACK: 'shipments.track',
  SHIPMENTS_BULK_UPDATE: 'shipments.bulk-update',
  SHIPMENTS_UPDATE_STATUS: 'shipments.update-status',

  MUSHAF_REQUESTS_CREATE: 'mushaf-requests.create',
  MUSHAF_REQUESTS_READ: 'mushaf-requests.read',
  MUSHAF_REQUESTS_UPDATE: 'mushaf-requests.update',
  MUSHAF_REQUESTS_DELETE: 'mushaf-requests.delete',
  MUSHAF_REQUESTS_APPROVE: 'mushaf-requests.approve',
  MUSHAF_REQUESTS_REJECT: 'mushaf-requests.reject',
  MUSHAF_REQUESTS_PROCESS: 'mushaf-requests.process',

  CERTIFICATES_CREATE: 'certificates.create',
  CERTIFICATES_READ: 'certificates.read',
  CERTIFICATES_UPDATE: 'certificates.update',
  CERTIFICATES_DELETE: 'certificates.delete',
  CERTIFICATES_GENERATE: 'certificates.generate',
  CERTIFICATES_DOWNLOAD: 'certificates.download',

  TEMPLATES_CREATE: 'templates.create',
  TEMPLATES_READ: 'templates.read',
  TEMPLATES_UPDATE: 'templates.update',
  TEMPLATES_DELETE: 'templates.delete',
  TEMPLATES_SET_DEFAULT: 'templates.set-default',
  TEMPLATES_TOGGLE: 'templates.toggle',

  WAREHOUSE_DASHBOARD: 'warehouse.dashboard',
  WAREHOUSE_PACKING_VIEW: 'warehouse.packing.view',
  WAREHOUSE_PACKING_SCAN: 'warehouse.packing.scan',
  WAREHOUSE_PACKING_SEAL: 'warehouse.packing.seal',
  WAREHOUSE_QR_GENERATE: 'warehouse.qr.generate',
  WAREHOUSE_QR_SCAN: 'warehouse.qr.scan',
  WAREHOUSE_QR_VERIFY: 'warehouse.qr.verify',
  WAREHOUSE_QR_BULK_GENERATE: 'warehouse.qr.bulk_generate',
  WAREHOUSE_PERFORMANCE_VIEW: 'warehouse.performance.view',
  WAREHOUSE_TASKS_VIEW: 'warehouse.tasks.view',
  WAREHOUSE_TASKS_UPDATE: 'warehouse.tasks.update',
  WAREHOUSE_BOXES_VIEW: 'warehouse.boxes.view',
  WAREHOUSE_BOXES_SEAL: 'warehouse.boxes.seal',
  WAREHOUSE_BOX_UPDATE_SEALED: 'warehouse.box.update_sealed',
  WAREHOUSE_BOX_UPDATE_ANY: 'warehouse.box.update_any',

  SUPERVISOR_DASHBOARD: 'supervisor.dashboard',
  SUPERVISOR_WAREHOUSE_MONITOR: 'supervisor.warehouse.monitor',
  SUPERVISOR_WAREHOUSE_REDISTRIBUTE: 'supervisor.warehouse.redistribute',
  SUPERVISOR_WAREHOUSE_ASSIGN: 'supervisor.warehouse.assign',
  SUPERVISOR_PERFORMANCE_VIEW: 'supervisor.performance.view',
  SUPERVISOR_PERFORMANCE_REPORTS: 'supervisor.performance.reports',

  QR_GENERATE: 'qr.generate',
  QR_SCAN: 'qr.scan',
  QR_VERIFY: 'qr.verify',

  STATUS_UPDATE: 'status.update',
  STATUS_TRACK: 'status.track',

  WAKAF_BATCH_CREATE: 'wakaf-batch.create',
  WAKAF_BATCH_READ: 'wakaf-batch.read',
  WAKAF_BATCH_UPDATE: 'wakaf-batch.update',
  WAKAF_BATCH_DELETE: 'wakaf-batch.delete',

  SETTINGS_READ: 'settings.read',
  SETTINGS_WRITE: 'settings.write',
  SETTINGS_DELETE: 'settings.delete',

  SYSTEM_MONITOR: 'system.monitor',
};
